site_name: ssslinppp-docs
pages:
    - Home: index.md
    - 'User Guide': 'xxx.md'
    - xxx:
      - xx3: index.md
      - xx4: xxx.md
    - mysql : about/mysql/mysqlIndex.md
    - About: about.md
#repo_url: https://github.com/ssslinppp/rtddocs.git

